### PR TITLE
Feat - more faster and choose how many like do you wants to swipe

### PR DESCRIPTION
**Pull request by brosscss**

### CODE REVIEW

**Comment by NetworkArchitect-sudo** [comment]
with random delay inbetween 5 secs

`var confirmBox = parseInt(prompt('How many likes do you want to send?'));
if (isNaN(confirmBox)) {
  alert('You must enter a number');
  throw new Error('You must enter a number');
}

var count = 0;

function randomDelay() {
  return Math.floor(Math.random() * (5000 - 1000 + 1)) + 1000; // Random delay between 1000ms and 5000ms
}

var like = function() {
  if (confirmBox > 0) {
    // Select the like button element and trigger a click event
    var likeBtn = document.querySelector('.encounters-action.tooltip-activator.encounters-action--like');
    if (likeBtn && likeBtn.offsetParent !== null) {
      if (count >= confirmBox) {
        console.log('Sent ' + count + ' likes');
        return;
      }
      likeBtn.click();
      count++;
      console.log('Like ' + count);
    } else {
      console.log('No "Like" button found or the button is not visible.');
    }
  }
  setTimeout(like, randomDelay()); // Schedule the next like with a random delay
};

setTimeout(like, randomDelay()); // Start the process with a random delay`

**Review by NetworkArchitect-sudo — COMMENTED** [review]
`var confirmBox = parseInt(prompt('How many likes do you want to send?'));
if (isNaN(confirmBox)) {
  alert('You must enter a number');
  throw new Error('You must enter a number');
}

var count = 0;

function randomDelay() {
  return Math.floor(Math.random() * (5000 - 1000 + 1)) + 1000; // Random delay between 1000ms and 5000ms
}

var like = function() {
  if (confirmBox > 0) {
    // Select the like button element and trigger a click event
    var likeBtn = document.querySelector('.encounters-action.tooltip-activator.encounters-action--like');
    if (likeBtn && likeBtn.offsetParent !== null) {
      if (count >= confirmBox) {
        console.log('Sent ' + count + ' likes');
        return;
      }
      likeBtn.click();
      count++;
      console.log('Like ' + count);
    } else {
      console.log('No "Like" button found or the button is not visible.');
    }
  }
  setTimeout(like, randomDelay()); // Schedule the next like with a random delay
};

setTimeout(like, randomDelay()); // Start the process with a random delay`

**Comment by amitoj-singh** [comment]
Hi @brosscss 

Thanks for your contribution. Apologies for responding late.

I liked the idea of random delay as suggested by @NetworkArchitect-sudo 

Can you please incorporate those changes and make a new commit please.

**Comment by NetworkArchitect-sudo** [comment]
Hi @amitoj-singh 
done

**Pull request closed without merging**
